package io.jentz.winter.inject

import io.jentz.winter.Component
import io.jentz.winter.Graph
import io.jentz.winter.TypeKey

/**
 * Interface implemented by factories generated by winter-compiler.
 */
interface Factory<R: Any> : (Graph) -> R {

    /**
     * Register the factory on the given [builder] instance.
     */
    fun register(builder: Component.Builder, override: Boolean): TypeKey<R>

}
